[application]

asset_dir = "assets"

[web.app]

# HTML title tag content
title = "dioxus-shadcn"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = ["/assets/tailwind.css"]

# Additional JavaScript files
script = ["/assets/syntax-highlight.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
