//! Documentation pages module.

pub mod components;
pub mod installation;
pub mod intro;
pub mod navigation;

pub use installation::InstallationDoc;
pub use intro::IntroDoc;

/// Documentation route - parsed from URL path.
#[derive(Clone, PartialEq, Debug, Default)]
#[allow(clippy::enum_variant_names)]
pub enum DocsRoute {
    #[default]
    IntroPage,
    InstallationPage,
    AccordionPage,
    AlertPage,
    AlertDialogPage,
    AspectRatioPage,
    AvatarPage,
    BadgePage,
    BreadcrumbPage,
    ButtonPage,
    ButtonGroupPage,
    CardPage,
    CarouselPage,
    CheckboxPage,
    CollapsiblePage,
    ComboboxPage,
    CommandPage,
    ContextMenuPage,
    DialogPage,
    DirectionPage,
    DrawerPage,
    DropdownPage,
    EmptyPage,
    FieldPage,
    FormPage,
    HoverCardPage,
    InputPage,
    InputGroupPage,
    InputOTPPage,
    ItemPage,
    KbdPage,
    LabelPage,
    MenubarPage,
    NativeSelectPage,
    NavigationMenuPage,
    PaginationPage,
    PopoverPage,
    ProgressPage,
    RadioGroupPage,
    ResizablePage,
    ScrollAreaPage,
    SelectPage,
    SeparatorPage,
    SideSheetPage,
    SkeletonPage,
    SliderPage,
    SpinnerPage,
    SwitchPage,
    TablePage,
    TabsPage,
    TextareaPage,
    ToastPage,
    TogglePage,
    ToggleGroupPage,
    TooltipPage,
}

impl DocsRoute {
    /// Parse a DocsRoute from URL segments.
    pub fn from_segments(segments: &[String]) -> Self {
        let segments: Vec<&str> = segments.iter().map(|s| s.as_str()).collect();
        match segments.as_slice() {
            [] | [""] => Self::IntroPage,
            ["installation"] => Self::InstallationPage,
            ["components", "accordion"] => Self::AccordionPage,
            ["components", "alert"] => Self::AlertPage,
            ["components", "alert-dialog"] => Self::AlertDialogPage,
            ["components", "aspect-ratio"] => Self::AspectRatioPage,
            ["components", "avatar"] => Self::AvatarPage,
            ["components", "badge"] => Self::BadgePage,
            ["components", "breadcrumb"] => Self::BreadcrumbPage,
            ["components", "button"] => Self::ButtonPage,
            ["components", "button-group"] => Self::ButtonGroupPage,
            ["components", "card"] => Self::CardPage,
            ["components", "carousel"] => Self::CarouselPage,
            ["components", "checkbox"] => Self::CheckboxPage,
            ["components", "collapsible"] => Self::CollapsiblePage,
            ["components", "combobox"] => Self::ComboboxPage,
            ["components", "command"] => Self::CommandPage,
            ["components", "context-menu"] => Self::ContextMenuPage,
            ["components", "dialog"] => Self::DialogPage,
            ["components", "direction"] => Self::DirectionPage,
            ["components", "drawer"] => Self::DrawerPage,
            ["components", "dropdown"] => Self::DropdownPage,
            ["components", "empty"] => Self::EmptyPage,
            ["components", "field"] => Self::FieldPage,
            ["components", "form"] => Self::FormPage,
            ["components", "hover-card"] => Self::HoverCardPage,
            ["components", "input"] => Self::InputPage,
            ["components", "input-group"] => Self::InputGroupPage,
            ["components", "input-otp"] => Self::InputOTPPage,
            ["components", "item"] => Self::ItemPage,
            ["components", "kbd"] => Self::KbdPage,
            ["components", "label"] => Self::LabelPage,
            ["components", "menubar"] => Self::MenubarPage,
            ["components", "native-select"] => Self::NativeSelectPage,
            ["components", "navigation-menu"] => Self::NavigationMenuPage,
            ["components", "pagination"] => Self::PaginationPage,
            ["components", "popover"] => Self::PopoverPage,
            ["components", "progress"] => Self::ProgressPage,
            ["components", "radio-group"] => Self::RadioGroupPage,
            ["components", "resizable"] => Self::ResizablePage,
            ["components", "scroll-area"] => Self::ScrollAreaPage,
            ["components", "select"] => Self::SelectPage,
            ["components", "separator"] => Self::SeparatorPage,
            ["components", "side-sheet"] => Self::SideSheetPage,
            ["components", "skeleton"] => Self::SkeletonPage,
            ["components", "slider"] => Self::SliderPage,
            ["components", "spinner"] => Self::SpinnerPage,
            ["components", "switch"] => Self::SwitchPage,
            ["components", "table"] => Self::TablePage,
            ["components", "tabs"] => Self::TabsPage,
            ["components", "textarea"] => Self::TextareaPage,
            ["components", "toast"] => Self::ToastPage,
            ["components", "toggle"] => Self::TogglePage,
            ["components", "toggle-group"] => Self::ToggleGroupPage,
            ["components", "tooltip"] => Self::TooltipPage,
            _ => Self::IntroPage,
        }
    }

    /// Get the URL path for this route.
    pub fn to_path(&self) -> &'static str {
        match self {
            Self::IntroPage => "/docs",
            Self::InstallationPage => "/docs/installation",
            Self::AccordionPage => "/docs/components/accordion",
            Self::AlertPage => "/docs/components/alert",
            Self::AlertDialogPage => "/docs/components/alert-dialog",
            Self::AspectRatioPage => "/docs/components/aspect-ratio",
            Self::AvatarPage => "/docs/components/avatar",
            Self::BadgePage => "/docs/components/badge",
            Self::BreadcrumbPage => "/docs/components/breadcrumb",
            Self::ButtonPage => "/docs/components/button",
            Self::ButtonGroupPage => "/docs/components/button-group",
            Self::CardPage => "/docs/components/card",
            Self::CarouselPage => "/docs/components/carousel",
            Self::CheckboxPage => "/docs/components/checkbox",
            Self::CollapsiblePage => "/docs/components/collapsible",
            Self::ComboboxPage => "/docs/components/combobox",
            Self::CommandPage => "/docs/components/command",
            Self::ContextMenuPage => "/docs/components/context-menu",
            Self::DialogPage => "/docs/components/dialog",
            Self::DirectionPage => "/docs/components/direction",
            Self::DrawerPage => "/docs/components/drawer",
            Self::DropdownPage => "/docs/components/dropdown",
            Self::EmptyPage => "/docs/components/empty",
            Self::FieldPage => "/docs/components/field",
            Self::FormPage => "/docs/components/form",
            Self::HoverCardPage => "/docs/components/hover-card",
            Self::InputPage => "/docs/components/input",
            Self::InputGroupPage => "/docs/components/input-group",
            Self::InputOTPPage => "/docs/components/input-otp",
            Self::ItemPage => "/docs/components/item",
            Self::KbdPage => "/docs/components/kbd",
            Self::LabelPage => "/docs/components/label",
            Self::MenubarPage => "/docs/components/menubar",
            Self::NativeSelectPage => "/docs/components/native-select",
            Self::NavigationMenuPage => "/docs/components/navigation-menu",
            Self::PaginationPage => "/docs/components/pagination",
            Self::PopoverPage => "/docs/components/popover",
            Self::ProgressPage => "/docs/components/progress",
            Self::RadioGroupPage => "/docs/components/radio-group",
            Self::ResizablePage => "/docs/components/resizable",
            Self::ScrollAreaPage => "/docs/components/scroll-area",
            Self::SelectPage => "/docs/components/select",
            Self::SeparatorPage => "/docs/components/separator",
            Self::SideSheetPage => "/docs/components/side-sheet",
            Self::SkeletonPage => "/docs/components/skeleton",
            Self::SliderPage => "/docs/components/slider",
            Self::SpinnerPage => "/docs/components/spinner",
            Self::SwitchPage => "/docs/components/switch",
            Self::TablePage => "/docs/components/table",
            Self::TabsPage => "/docs/components/tabs",
            Self::TextareaPage => "/docs/components/textarea",
            Self::ToastPage => "/docs/components/toast",
            Self::TogglePage => "/docs/components/toggle",
            Self::ToggleGroupPage => "/docs/components/toggle-group",
            Self::TooltipPage => "/docs/components/tooltip",
        }
    }

    /// Get the title for the current route.
    pub fn title(&self) -> &'static str {
        match self {
            Self::IntroPage => "Introduction",
            Self::InstallationPage => "Installation",
            Self::AccordionPage => "Accordion",
            Self::AlertPage => "Alert",
            Self::AlertDialogPage => "Alert Dialog",
            Self::AspectRatioPage => "Aspect Ratio",
            Self::AvatarPage => "Avatar",
            Self::BadgePage => "Badge",
            Self::BreadcrumbPage => "Breadcrumb",
            Self::ButtonPage => "Button",
            Self::ButtonGroupPage => "Button Group",
            Self::CardPage => "Card",
            Self::CarouselPage => "Carousel",
            Self::CheckboxPage => "Checkbox",
            Self::CollapsiblePage => "Collapsible",
            Self::ComboboxPage => "Combobox",
            Self::CommandPage => "Command",
            Self::ContextMenuPage => "Context Menu",
            Self::DialogPage => "Dialog",
            Self::DirectionPage => "Direction",
            Self::DrawerPage => "Drawer",
            Self::DropdownPage => "Dropdown",
            Self::EmptyPage => "Empty",
            Self::FieldPage => "Field",
            Self::FormPage => "Form",
            Self::HoverCardPage => "Hover Card",
            Self::InputPage => "Input",
            Self::InputGroupPage => "Input Group",
            Self::InputOTPPage => "Input OTP",
            Self::ItemPage => "Item",
            Self::KbdPage => "Kbd",
            Self::LabelPage => "Label",
            Self::MenubarPage => "Menubar",
            Self::NativeSelectPage => "Native Select",
            Self::NavigationMenuPage => "Navigation Menu",
            Self::PaginationPage => "Pagination",
            Self::PopoverPage => "Popover",
            Self::ProgressPage => "Progress",
            Self::RadioGroupPage => "Radio Group",
            Self::ResizablePage => "Resizable",
            Self::ScrollAreaPage => "Scroll Area",
            Self::SelectPage => "Select",
            Self::SeparatorPage => "Separator",
            Self::SideSheetPage => "Side Sheet",
            Self::SkeletonPage => "Skeleton",
            Self::SliderPage => "Slider",
            Self::SpinnerPage => "Spinner",
            Self::SwitchPage => "Switch",
            Self::TablePage => "Table",
            Self::TabsPage => "Tabs",
            Self::TextareaPage => "Textarea",
            Self::ToastPage => "Toast",
            Self::TogglePage => "Toggle",
            Self::ToggleGroupPage => "Toggle Group",
            Self::TooltipPage => "Tooltip",
        }
    }

    /// Get the section name for breadcrumbs.
    pub fn section(&self) -> &'static str {
        match self {
            Self::IntroPage | Self::InstallationPage => "Getting Started",
            _ => "Components",
        }
    }
}
